version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: npc_grafana
    networks:
    - npc
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    container_name: npc_influxdb
    networks:
    - npc
    ports:
    - 8086:8086
    volumes:
    - influxdb:/var/lib/influxdb2
    - influxdb_config:/etc/influxdb2

  app:
    image: hsttutorials/npc:latest
    container_name: npc_app
    networks:
    - npc
    volumes:
    - ./config.json:/app/config/config.json

networks:
  npc:

volumes:
  grafana:
  influxdb:
  influxdb_config:
