{
 "title": "Network performance",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Max latency  - last hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"npc_latency\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latency\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt_avg\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"google.com\")\r\n  |> aggregateWindow(every: 1h, fn: max, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Max Bandwidth - last hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"npc_fast.com\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fast.com\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"download\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"fast.com\")\r\n  |> aggregateWindow(every: 1h, fn: max, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"npc_latency\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latency\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt_avg\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"google.com\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"npc_fast.com\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fast.com\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"download\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"fast.com\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}